export const PLAYER_PHOTOS: Record<string, string> = {
  "A.J. Brown": "/player-avatars/aj_brown.webp",
  "Adonai Mitchell": "/player-avatars/adonai_mitchell.jpeg",
  "Amon-Ra St. Brown": "/player-avatars/amonra_stbrown.jpeg",
  "Bhayshul Tuten": "/player-avatars/bhayshul_tuten.webp",
  "Bijan Robinson": "/player-avatars/bijan_robinson.jpeg",
  "Blake Corum": "/player-avatars/blake_corum.jpeg",
  "Brock Purdy": "/player-avatars/brock_purdy.webp",
  "Carnell Tate": "/player-avatars/carnell_tate.webp",
  "CeeDee Lamb": "/player-avatars/ceedee_lamb.jpeg",
  "Chase Brown": "/player-avatars/chase_brown.jpeg",
  "Chris Olave": "/player-avatars/chris_olave.webp",
  "Chubba Hubbard": "/player-avatars/chubba_hubbard.jpeg",
  "D'Andre Swift": "/player-avatars/deandre_swift.jpeg",
  "Dalton Kincaid": "/player-avatars/dalton_kincaid.jpeg",
  "DeVonta Smith": "/player-avatars/devonta_smith.avif",
  "Deebo Samuel": "/player-avatars/deebo_samuel.jpg",
  "Deebo Samuel Sr.": "/player-avatars/deebo_samuel.jpg",
  "Denzel Boston": "/player-avatars/denzel_boston.jpeg",
  "Derrick Henry": "/player-avatars/images.jpeg",
  "Dak Prescott": "/player-avatars/dak_prescott.webp",
  "David Montgomery": "/player-avatars/david_montgomery.jpeg",
  "George Pickens": "/player-avatars/george_pickens.webp",
  "Jahmyr Gibbs": "/player-avatars/jahmyr_gibbs.jpg",
  "Ja'Marr Chase": "/player-avatars/jamar_chase.avif",
  "Javonte Williams": "/player-avatars/javonte_williams.webp",
  "Josh Jacobs": "/player-avatars/josh_jacobs.webp",
  "Justin Herbert": "/player-avatars/justin_herbert.jpg",
  "Kirk Cousins": "/player-avatars/kirk_cousins.webp",
  "Kyle Monangai": "/player-avatars/kyle_monangai.jpeg",
  "Lamar Jackson": "/player-avatars/lamar_jackson.avif",
  "Matthew Stafford": "/player-avatars/matthew_stafford.jpeg",
  "Parker Washington": "/player-avatars/parker_washington.jpeg",
  "Puka Nacua": "/player-avatars/puka_nacua.png",
  "Quinshon Judkins": "/player-avatars/quinshon_judkins.jpeg",
  "Rhamondre Stevenson": "/player-avatars/rhamondre_stevenson.jpeg",
  "Rico Dowdle": "/player-avatars/rico_dowdle.webp",
  "Saquon Barkley": "/player-avatars/saquon_barkley.jpeg",
  "Tetairoa McMillan": "/player-avatars/tet_mcmillan.webp",
  "Tony Pollard": "/player-avatars/tony_pollard.jpeg",
  "TreVeyon Henderson": "/player-avatars/treveyon_henderson.webp",
  "Tucker Kraft": "/player-avatars/tucker_kraft.webp",
  "Zay Flowers": "/player-avatars/zay_flower.jpeg",
};

export function teamColors(): [string, string] {
  return ["#171717", "#e5e5e5"];
}
